name: Build Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: linux
          - os: macos-latest
            artifact_name: macos
          - os: windows-latest
            artifact_name: windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --name AcgDraw \
          main.py
        # Windows 需要处理路径分隔符
        if [ "${{ runner.os }}" == "Windows" ]; then
          mv dist/myapp.exe dist/myapp-windows.exe
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ matrix.artifact_name }}
        path: dist/